#radixconfig production
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismic
spec:
  environments:
    # stable production branch users are supposed to use
    - name: prod
      build:
        from: radix
    # environment that can be used for performance testing
    # environment must be stopped when not needed
    - name: test
      build:
        from: radix_test
  components:
    - name: server
      dockerfileName: Dockerfile
      ports:
        - name: http
          port: 8080
        - name: metrics
          port: 8081
      publicPort: http
      monitoringConfig:
        portName: metrics
      identity:
        azure:
          clientId: fd162526-89a0-448a-979f-655c0717db52
      environmentConfig:
        - environment: prod
          variables:
            VDSSLICE_PORT: 8080
            VDSSLICE_CACHE_SIZE: 512 # MB
            VDSSLICE_METRICS: true
            VDSSLICE_METRICS_PORT: 8081
            VDSSLICE_TRUSTED_PROXIES: ""
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: prod-allowlist
                    envVar: VDSSLICE_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "8192Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
        - environment: test
          replicas: 0
          variables:
            VDSSLICE_PORT: 8080
            VDSSLICE_CACHE_SIZE: 0 # MB
            VDSSLICE_METRICS: true
            VDSSLICE_METRICS_PORT: 8081
            VDSSLICE_TRUSTED_PROXIES: ""
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: test-allowlist
                    envVar: VDSSLICE_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "8192Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
