apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismictest
spec:
  environments:
    - name: dev
      build:
        from: radix
    - name: test
      build:
        from: test
  components:
    - name: server
      dockerfileName: Dockerfile
      secrets:
        - VDSSLICE_STORAGE_ACCOUNTS
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: dev
          monitoring: false
          resources:
            requests:
              memory: "2048Mi"
              cpu: "500m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
        - environment: test
          monitoring: false
          resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          horizontalScaling:
            # Radix doesn't scale to 0, so this is just desired intention
            minReplicas: 0
            maxReplicas: 3
